# ===============================================================================
# = Copyright (C) 2026 Kurv Cygnus                                              =
# = This file is part of Crisp Sweetberry.                                      =
# = Crisp Sweetberry is free software: you can redistribute it and/or modify    =
# = it under the terms of the GNU Lesser General Public License as published by =
# = the Free Software Foundation, either version 3 of the License.              =
# ===============================================================================

#? This is the metainfo configuration of this mod, CrispSweetberry,
#? which stores the Loader Version, Mod Name, Dependency, Mixin Configs, etc.

#* Mixin Index:
#* 1. Spyglass Mixin [[../crispsweetberry.spyglass.mixins.json]]
#* 2. T Torch Series Mixin [[../crispsweetberry.ttorches.mixins.json]]
#* 3. Carry Crate Mixin [[../crispsweetberry.carrycrate.mixins.json]]

modLoader="javafml"

loaderVersion="${loader_version_range}"

license="GNU GPLv3"

[[mods]]
modId="crispsweetberry"
version="1.0 Release"
displayName="Crisp Sweetberry"

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

displayURL="https://github.com/KurvCygnus/CrispSweetberry/"

logoFile="mod_title.png"

#credits=""

authors="Kurv Cygnus"

description='Crisp Sweetberry is a mod that focuses on vanilla enchancements, adding vanilla-style stuffs.'

[[mixins]]
config="crispsweetberry.spyglass.mixins.json"

[[mixins]]
config="crispsweetberry.ttorches.mixins.json"

[[mixins]]
config="crispsweetberry.carrycrate.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.crispsweetberry]]
    modId="neoforge"
    # The componentExecutionType of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
    # 'required' requires the mod to exist, 'optional' does not
    # 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
    type="required"
    # Optional field describing why the dependency is required or why it is incompatible
    # reason="..."
    # The version range of the dependency
    versionRange="[${neo_version},)" #mandatory
    # An ordering relationship for the dependency.
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"

[[dependencies.crispsweetberry]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

#[[dependencies.crispsweetberry]]
#    modId = "lambdynlights_api"
#    componentExecutionType = "optional"
#    versionRange = "PlaceHolder"
#    ordering = "BEFORE"
#    side = "CLIENT"
#
#[[dependencies.crispsweetberry]]
#    modId = "jei"
#    componentExecutionType = "optional"
#    versionRange = "PlaceHolder"
#    ordering = "BEFORE"
#    side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
