//==============================================================================
// Copyright (C) 2026 Kurv Cygnus                                              =
// This file is part of Crisp Sweetberry.                                      =
// Crisp Sweetberry is free software: you can redistribute it and/or modify    =
// it under the terms of the GNU Lesser General Public License as published by =
// the Free Software Foundation, either version 3 of the License.              =
//==============================================================================

package kurvcygnus.crispsweetberry.annotation.processor;

import kurvcygnus.crispsweetberry.annotations.AutoI18n;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import javax.tools.Diagnostic;
import javax.tools.StandardLocation;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.*;
import java.util.function.BinaryOperator;
import java.util.regex.Matcher;

import static kurvcygnus.crispsweetberry.annotations.AutoI18n.Lang;
import static kurvcygnus.crispsweetberry.annotations.AutoI18n.TRANSLATION_PATTERN;

//? TODO: Group Translation Override Logic

/**
 * This is the processor of annotation <u>{@link AutoI18n}</u>, it iterates, checks, collects, and finally generates 
 * the language files.
 * @since 1.0 Release
 * @author Kurv Cygnus
 * @see AutoI18n Annotation
 */
@SupportedAnnotationTypes("kurvcygnus.crispsweetberry.annotations.AutoI18n")
@SupportedSourceVersion(SourceVersion.RELEASE_21)//? TODO: Move to Minecraft 26.1, with java 25!!!!!!! No need to compat YarnMap!
@SupportedOptions({"i18nPath", "modid"})
public final class I18nProcessor extends AbstractProcessor
{
    //region Constants, Fields & Initialization
    static final int UNSUPPORTED_INDEX = -1;
    
    private static final String VERSION = "v0.2";
    private static final String STANDARD_GENERATE_HEADER = """
        {
            "Generated by": "Crispsweetberry-i18n-processor:%s, DO NOT EDIT",
        """.formatted(VERSION);
    private static final String UWU_HADR = """
        {
            "thz iz": "TA2TY FRUT uwu, vrshen: %s, nah taoch tiz or kat wil biat ya!",
        """.formatted(VERSION);
    private static final BinaryOperator<String> ENTRY_TEMPLATE = (key, value) -> "    \"%s\": \"%s\"".formatted(key, escape(value));
    
    /**
     * <u>{@link Messager}</u> is the logger of Compile-Time.<br><br>
     * Different from normal coding, <u>{@link AbstractProcessor annotation processor}</u> can't use loggers because 
     * context passing issues, and more importantly, <u>{@link Messager#printMessage(Diagnostic.Kind, CharSequence)}</u> can 
     * terminate compile and throw error when <u>{@link javax.tools.Diagnostic.Kind Diagnostic Kind}</u> is <u>{@link javax.tools.Diagnostic.Kind#ERROR ERROR}</u>, 
     * this is essential in <u>{@link AbstractProcessor annotation processor}</u>, despite directly use {@code throw new MyException} will also terminate the compile,
     * however, it will splat a lot of garbage error stack traces to make your head explode in the end.<br><br>
     * Thus, using <u>{@link Messager}</u> to log stuff is basically a must in <u>{@link AbstractProcessor annotation processor}</u>.
     */
    private Messager messager;
    private Filer filer;
    
    /**
     * <u>{@link Types}</u> is the utility of <u>{@link TypeMirror}</u>, it is a must in deducing detailed types.
     * @see Types
     */
    private Types typeUtil;
    
    private String namespace;
    private TypeMirror object;
    
    /**
     * All actually nullable. This can be caused by incorrect configuration of dependency, and other reasons.<br>
     * In <u>{@link ProcessableType#getSafeTypeMirror(Elements, TypeMirror)}</u>, we replaced null with <u>{@link Object}</u>'s <u>{@link TypeMirror}</u> to make sure helper methods
     * are safe to use.
     */
    private List<TypeMirror> types;
    
    private final HashMap<String, HashMap<Lang, String>> groups = new HashMap<>();
    private final HashMap<String, HashMap<Lang, String>> translationLookup = new HashMap<>();
    
    private @Nullable String outputPath;
    private boolean generated = false;
    
    @Override public synchronized void init(@NotNull ProcessingEnvironment processingEnv)
    {
        super.init(processingEnv);
        this.messager = processingEnv.getMessager();
        this.filer = processingEnv.getFiler();
        this.typeUtil = processingEnv.getTypeUtils();
        final Elements elementUtil = processingEnv.getElementUtils();
        this.namespace = processingEnv.getOptions().get("modid");
        this.object = elementUtil.getTypeElement(ProcessableType.UNSUPPORTED.fqcn).asType();
        this.types = ProcessableType.initializeTypes(elementUtil, this.object);
        this.outputPath = processingEnv.getOptions().get("i18nPath");
        
        if(!hasContent(namespace) || namespace.equals("unknown"))
            printError(
                """
                    Unknown namespace. Go to build.gradle and configure it first.
                    
                    Example:
                    ```
                    java {
                        tasks.withType(JavaCompile).configureEach {
                            options.compilerArgs.add("-Amodid=" + (project.findProperty('mod_id') ?: 'unknown'))
                        }
                    }
                    ```
                    Having other issues? Please feed back at %PLACEHOLDER%.
                    """
            );
        
        if(!hasContent(outputPath) || outputPath.equals("default"))
        {
            printError(
                    """
                    Current using default output path: "${targetModule}/build/generated/sources/annotationProcessor/java/main/assets/%s/lang/".
                    
                    We recommend using configured path to prevent the unnecessary manual work.
                    Example:
                    ```
                    java {
                        tasks.withType(JavaCompile).configureEach {
                            options.compilerArgs.add("-Ai18nPath=" + (project.findProperty('i18n_path') ?: 'default'))
                        }
                    }
                    ```
                    Don't forget to add config to your gradle.properties:
                    ```
                    i18n_path=${your_path}
                    // Use absolute path instead of relative path.
                    // Also, don't leek your absolute path on github XD
                    ```
                    """.formatted(namespace)
            );
            outputPath = null;
        }
    }
    //endregion
    
    //region Procession Logics
    @Override public boolean process(@NotNull Set<? extends TypeElement> annotations, @NotNull RoundEnvironment roundEnv)
    {
        if(roundEnv.processingOver() && !generated)
        {
            generated = true;//! Process only once.
            this.generateJSON(this.composeTranslationTable());
            return false;
        }
        
        if(annotations.isEmpty())
            return false;
        
        for(final Element element: roundEnv.getElementsAnnotatedWith(AutoI18n.class))
        {
            if(element.getKind() != ElementKind.FIELD)
                printError(
                    "%s must be a field.".formatted(element.getSimpleName().toString()),
                    element
                );
            
            final @Nullable AutoI18n autoI18n = element.getAnnotation(AutoI18n.class);
            
            if(autoI18n == null)
            {
                messager.printMessage(
                    Diagnostic.Kind.WARNING,
                    "Processing exception: The AutoI18n annotation of %s seems to be null. Skipped.".formatted(element.getSimpleName().toString()),
                    element
                );
                
                continue;//* Theoretically unachievable.
            }
            
            final String group = autoI18n.group();
            final String[] translations = autoI18n.value();
            final String key = autoI18n.key().isBlank() ?
                element.getSimpleName().toString().toLowerCase().replace("__", ".") :
                autoI18n.key();
            
            final String fullKeyScope = parseKeyScope(new ParseContext(namespace, key, element, element.asType(), this::printError, typeUtil, types));
            
            if(!hasContent(group) && !hasContent(translations))
                printError(
                    "%s doesn't have a group, and has no translations, or translations include an illegal string.".formatted(element.getSimpleName().toString()),
                    element
                );
            
            final boolean hasTranslation = hasContent(translations);
            final boolean hasGroup = hasContent(group);
            
            this.parseTranslations(element, hasTranslation ? translations : null, fullKeyScope, hasGroup ? group : null);
        }
        
        return true;
    }
    
    private @NotNull String parseKeyScope(@NotNull ParseContext context)
        { return ProcessableType.getType(inTypes(context.elementType())).parse(context, this::parseKeyScope); }
    
    private void parseTranslations(@NotNull Element element, String @Nullable [] translations, @NotNull String key, @Nullable String group)
    {
        HashMap<Lang, String> translationContent = new HashMap<>();
        
        if(translations != null)
        {
            for(int index = 0; index < translations.length; index++)
            {
                final String translation = translations[index];
                final Matcher matcher = TRANSLATION_PATTERN.matcher(translation);
                
                if(!matcher.matches())
                    printError(
                        "Mismatched translation grammar: %s -> at %s, index %d".formatted(translation, element.getSimpleName().toString(), index),
                        element
                    );
                
                final String lang = matcher.group(1);
                final String content = matcher.group(2).replace("&ensp;", " ");
                
                if(!hasContent(lang))
                    printError(
                        "Language is empty -> at %s, index %d".formatted(element.getSimpleName().toString(), index),
                        element
                    );
                
                if(!hasContent(content))
                    printError(
                        "Content is empty -> at %s, index %d".formatted(element.getSimpleName().toString(), index),
                        element
                    );
                
                final Optional<Lang> language = Lang.parse(lang);
                
                if(language.isPresent())
                    translationContent.put(language.get(), content);
                else
                    printError("Language %s doesn't exist!".formatted(lang), element);
            }
        }
        
        if(group != null)
        {
            final String fullGroup = "%s:%s".formatted(namespace, group);
            
            if(!translationContent.isEmpty())//* Initialize group case.
            {
                if(groups.containsKey(fullGroup))
                    printError("Group %s has been defined for multiple times!".formatted(fullGroup));
                
                groups.put(fullGroup, translationContent);
            }
            else//* Use group case.
            {
                if(!groups.containsKey(fullGroup))
                    printError(
                        "Group \"%s\" doesn't exist in cached groups!".formatted(fullGroup),
                        element
                    );
                    
                translationContent = groups.get(fullGroup);
            }
        }
        
        if(translationLookup.keySet().stream().anyMatch(k -> k.equals(key)))
            printError(
                "Key %s has been defined for multiple times!".formatted(key),
                element
            );
        
        //* Neither this parsed content belongs to a group, it should always be added to table.
        translationLookup.put(key, translationContent);
    }
    
    private @NotNull HashMap<Lang, HashMap<String, String>> composeTranslationTable()
    {
        final HashMap<Lang, HashMap<String, String>> translationTable = new HashMap<>();
        for(final var set: translationLookup.entrySet())
        {
            final String key = set.getKey();
            final HashMap<Lang, String> contents = set.getValue();
            
            for(final var contentEntry: contents.entrySet())
            {
                final Lang lang = contentEntry.getKey();
                final String content = contentEntry.getValue();
                
                final HashMap<String, String> map = translationTable.computeIfAbsent(lang, $ -> new HashMap<>());
                
                if(map.containsKey(key))
                    printError("Duplicated translation key -> key: %s".formatted(key));
                
                map.put(key, content);
            }
        }
        return translationTable;
    }
    
    private void generateJSON(@NotNull HashMap<Lang, HashMap<String, String>> translationTable)
    {
        translationTable.forEach(
            (lang, translationMap) ->
            {
                try(final var writer = getWriter(lang))
                {
                    final String generatedHeader = lang.equals(Lang.LOL_US) ? UWU_HADR : STANDARD_GENERATE_HEADER;
                    
                    writer.write(generatedHeader);
                    final List<String> keys = new ArrayList<>(translationMap.keySet());
                    keys.sort(String::compareTo);
                    
                    for(int index = 0; index < keys.size(); index++)
                    {
                        final String key = keys.get(index);
                        final String content = translationMap.get(key);
                        final String entry = ENTRY_TEMPLATE.apply(key, content);
                        writer.write(entry);
                        
                        if(index < keys.size() - 1)
                            writer.write(",");
                        writer.write("\n");
                    }
                    
                    writer.write("}");
                    messager.printMessage(
                        Diagnostic.Kind.NOTE,
                        "Generated %s.json.".
                            formatted(lang.getCode())
                    );
                }
                catch(IOException e) { printError("Can't create JSON file. Details: %s".formatted(e.getMessage())); }
            }
        );
    }
    //endregion
    
    //region Private Utils
    private void printError(@NotNull String message) { this.printError(message, null); }
    
    private void printError(@NotNull String message, @Nullable Element element)
    {
        if(element == null)
            this.messager.printMessage(Diagnostic.Kind.ERROR, message);
        else
            this.messager.printMessage(Diagnostic.Kind.ERROR, message, element);
    }
    
    private @NotNull Writer getWriter(@NotNull Lang lang) throws IOException
    {
        if(this.outputPath == null)
        {
            return filer.createResource(
                StandardLocation.SOURCE_OUTPUT,
                "",
                "assets/%s/lang/%s.json".formatted(this.namespace, lang.getCode())
            ).openWriter();
        }
        
        final File dir = new File(this.outputPath, "assets/%s/lang/".formatted(this.namespace));
        
        if(!dir.exists() && !dir.mkdirs())
            printError("Can't create directory: %s".formatted(this.outputPath));
        
        final File file = new File(dir, "%s.json".formatted(lang.getCode()));
        
        return new BufferedWriter(new OutputStreamWriter(Files.newOutputStream(file.toPath()), StandardCharsets.UTF_8));
    }
    
    private static @NotNull String escape(@NotNull String text)
    {
        return text.replace("\\", "\\\\").
            replace("\"", "\\\"").
            replace("\n", "\\n").
            replace("\r", "\\r").
            replace("\t", "\\t");
    }
    
    @Contract(value = "null -> false", pure = true)
    @SuppressWarnings("BooleanMethodIsAlwaysInverted")//! Inverting name will make meaning of this method confusing.
    private static boolean hasContent(@Nullable String string) { return string != null && !string.isBlank(); }
    
    @Contract(value = "null -> false", pure = true)
    private static boolean hasContent(@Nullable String @Nullable [] strings)
    {
        if(strings == null)
            return false;
        
        for(final @Nullable String string: strings)
            if(!hasContent(string))
                return false;
        
        return true;
    }
    
    private int inTypes(@NotNull TypeMirror mirror)
    {
        for(int index = 0; index < types.size(); index++)
        {
            final @Nullable TypeMirror typeMirror = typeUtil.erasure(types.get(index));
            
            if(typeUtil.isSameType(typeMirror, object))
            {
                printError("The type at index %d seems to be null. Stopping procession.".formatted(index));
                return UNSUPPORTED_INDEX;
            }
            
            if(typeUtil.isAssignable(mirror, typeMirror))
                return index;
        }
        
        return UNSUPPORTED_INDEX;
    }
    //endregion
}
