//==============================================================================
// Copyright (C) 2026 Kurv Cygnus                                              =
// This file is part of Crisp Sweetberry.                                      =
// Crisp Sweetberry is free software: you can redistribute it and/or modify    =
// it under the terms of the GNU Lesser General Public License as published by =
// the Free Software Foundation, either version 3 of the License.              =
//==============================================================================

package kurvcygnus.crispsweetberry.annotation.processor;

import kurvcygnus.crispsweetberry.annotations.AutoI18n;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import javax.tools.Diagnostic;
import javax.tools.StandardLocation;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import java.util.function.BinaryOperator;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static kurvcygnus.crispsweetberry.annotations.AutoI18n.Lang;

/*
 TODO:
 [x] Stricter, and better error check.
 [ ] Support `~@d{textToDiscard}` for [[AutoI18n#key]].
 [ ] Support `~@s{length}`.
 [ ] Consider `~~@` to escape??? TBH, will there really someone write strange stuff like this?
 [ ] [[I18nProcessor#parseTranslations]] may need refactor in the future...
*/

//? TODO: Moving to Minecraft 26.2, with java 25!!!!!!! No need to compat YarnMap!

/**
 * This is the processor of annotation <u>{@link AutoI18n}</u>, it iterates, checks, collects, and finally generates 
 * the language files.
 * @since 1.0 Release
 * @author Kurv Cygnus
 * @see AutoI18n Annotation
 */
@SupportedAnnotationTypes("kurvcygnus.crispsweetberry.annotations.AutoI18n")
@SupportedSourceVersion(SourceVersion.RELEASE_21)
@SupportedOptions({"i18nPath", "modid"})
public final class I18nProcessor extends AbstractProcessor
{
    //region Constants, Fields & Initialization
    static final int UNSUPPORTED_INDEX = -1;
    
    private static final String VERSION = "v0.3";
    private static final String STANDARD_GENERATE_HEADER = """
        {
            "Generated by": "Crispsweetberry-i18n-processor:%s, DO NOT EDIT",
        """.formatted(VERSION);
    private static final String UWU_HADR = """
        {
            "thz iz": "TA2TY FRUT uwu, vrshen: %s, nah taoch tiz or kat wil biat ya!",
        """.formatted(VERSION);
    private static final BinaryOperator<String> ENTRY_TEMPLATE = (key, value) -> "    \"%s\": \"%s\"".formatted(key, escape(value));
    
    private static final String SUPER = "~@^";
    private static final String WHITESPACE = "~@s";
    private static final Pattern TRANSLATION_PATTERN = Pattern.compile("^\\s*([a-zA-Z._]+)\\s*=\\s*(.+?)\\s*$", Pattern.DOTALL);
    
    /**
     * <u>{@link Messager}</u> is the logger of Compile-Time.<br><br>
     * Different from normal coding, <u>{@link AbstractProcessor annotation processor}</u> can't use loggers because
     * context passing issues, and more importantly, <u>{@link Messager#printMessage(Diagnostic.Kind, CharSequence)}</u> can
     * terminate compile and throw error when <u>{@link javax.tools.Diagnostic.Kind Diagnostic Kind}</u> is <u>{@link javax.tools.Diagnostic.Kind#ERROR ERROR}</u>,
     * this is essential in <u>{@link AbstractProcessor annotation processor}</u>, despite directly use {@code throw new MyException} will also terminate the compile,
     * however, it will splat a lot of garbage error stack traces to make your head explode in the end.<br><br>
     * Thus, using <u>{@link Messager}</u> to log stuff is basically a must in <u>{@link AbstractProcessor annotation processor}</u>.
     */
    private final LazyVariable<Messager> messager = LazyVariable.create();
    private final LazyVariable<Filer> filer = LazyVariable.create();
    
    /**
     * <u>{@link Types}</u> is the utility of <u>{@link TypeMirror}</u>, it is a must in deducing detailed types.
     * @see Types
     */
    private final LazyVariable<Types> typeUtil = LazyVariable.create();
    
    private final LazyVariable<String> namespace = LazyVariable.create();
    private final LazyVariable<TypeMirror> object = LazyVariable.create();
    
    /**
     * All actually nullable. This can be caused by incorrect configuration of dependency, and other reasons.<br>
     * In <u>{@link ProcessableType#getSafeTypeMirror(Elements, TypeMirror)}</u>, we replaced null with <u>{@link Object}</u>'s <u>{@link TypeMirror}</u> to make sure helper methods
     * are safe to use.
     */
    private List<TypeMirror> types;
    
    private final HashMap<String, HashMap<Lang, String>> groups = new HashMap<>();
    private final HashMap<String, HashMap<Lang, String>> translationLookup = new HashMap<>();
    
    private @Nullable String outputPath;
    private boolean generated = false;
    
    @Override public synchronized void init(@NotNull ProcessingEnvironment processingEnv)
    {
        super.init(processingEnv);
        final Elements elementUtil = processingEnv.getElementUtils();
        
        this.messager.bound(processingEnv.getMessager());
        this.filer.bound(processingEnv.getFiler());
        this.typeUtil.bound(processingEnv.getTypeUtils());
        this.namespace.bound(processingEnv.getOptions().get("modid"));
        this.object.bound(elementUtil.getTypeElement(ProcessableType.UNSUPPORTED.fqcn).asType());
        this.types = ProcessableType.initializeTypes(elementUtil, this.object.get());
        this.outputPath = processingEnv.getOptions().get("i18nPath");
        
        if(!hasContent(namespace.get()) || namespace.get().equals("unknown"))
            printError(
                """
                    Can't get the namespace of this project.
                    This may be caused by:
                    
                    1. The param hasn't been configured.
                    
                    Example:
                    ```
                    java {
                        tasks.withType(JavaCompile).configureEach {
                            options.compilerArgs.add("-Amodid=" + (project.findProperty('mod_id') ?: 'unknown'))
                        }
                    }
                    ```
                    
                    2. The namespace is not specfied in gradle.properties.
                    
                    Example:
                    ```
                    mod_id=foobarbaz
                    ```
                    
                    Having other issues? Please feed back at https://github.com/KurvCygnus/CrispSweetberry/issues.
                    """
            );
        
        if(!hasContent(outputPath) || outputPath.equals("default"))
        {
            printError(
                """
                    Current using default output path: "${targetModule}/build/generated/sources/annotationProcessor/java/main/assets/%s/lang/".
                    
                    We recommend using configured path to prevent the unnecessary manual work.
                    Example:
                    ```
                    java {
                        tasks.withType(JavaCompile).configureEach {
                            options.compilerArgs.add("-Ai18nPath=" + (project.findProperty('i18n_path') ?: 'default'))
                        }
                    }
                    ```
                    Don't forget to add config to your gradle.properties:
                    ```
                    i18n_path=${your_path}
                    # Use absolute path instead of relative path.
                    # Also, don't leek your absolute path on github XD
                    ```
                    """.formatted(namespace)
            );
            outputPath = null;
        }
        else if(!new File(outputPath).isDirectory())
            printError(
                "Current path: \"%s\" is unusable.\n This can caused by access property, non-existence of directory, and the instance path refers to is a file."
                    .formatted(outputPath)
            );
    }
    //endregion
    
    //region Procession Logics
    @Override public boolean process(@NotNull Set<? extends TypeElement> annotations, @NotNull RoundEnvironment roundEnv)
    {
        if(roundEnv.processingOver() && !generated)
        {
            generated = true;//! Process only once.
            this.generateJSON(this.composeTranslationTable());
            return false;
        }
        
        if(annotations.isEmpty())
            return false;
        
        for(final Element element: roundEnv.getElementsAnnotatedWith(AutoI18n.class))
        {
            if(element.getKind() != ElementKind.FIELD)
                printError(
                    "%s must be a field.".formatted(element.getSimpleName().toString()),
                    element
                );
            
            final @Nullable AutoI18n autoI18n = element.getAnnotation(AutoI18n.class);
            
            if(autoI18n == null)
            {
                messager.get().printMessage(
                    Diagnostic.Kind.WARNING,
                    "Processing exception: The AutoI18n annotation of %s seems to be null. Skipped.".formatted(element.getSimpleName().toString()),
                    element
                );
                
                continue;
            }
            
            final String group = autoI18n.group();
            final String overrides = autoI18n.overrides();
            final String[] translations = autoI18n.value();
            final String key = autoI18n.key().isBlank() ?
                element.getSimpleName().toString().toLowerCase().replace("__", ".") :
                autoI18n.key();
            
            final String fullKeyScope = parseKeyScope(new ParseContext(namespace.get(), key, element, element.asType(), this::printError, typeUtil.get(), types));
            
            if(!hasContent(translations) && !hasContent(group) && !hasContent(overrides))
                printError(
                    "%s doesn't have a group or inherited any group, and has no translations, or translations include an illegal string.".
                        formatted(element.getSimpleName().toString()),
                    element
                );
            
            this.parseTranslations(
                element,
                getOrNull(translations),
                fullKeyScope,
                getOrNull(group),
                getOrNull(overrides)
            );
        }
        
        return true;
    }
    
    private @NotNull String parseKeyScope(@NotNull ParseContext context)
        { return ProcessableType.getType(inTypes(context.elementType())).parse(context, this::parseKeyScope); }
    
    private void parseTranslations(@NotNull Element element, @Nullable String @Nullable [] translations, @NotNull String key, @Nullable String group, @Nullable String overrides)
    {
        final var currentDefinedContents = parseTranslationContents(element, translations, overrides);
        final var finalContents = new HashMap<Lang, String>();
        
        if(overrides != null)
        {
            final var overriddenGroup = "%s:%s".formatted(namespace, overrides);
            final @Nullable var baseContents = groups.get(overriddenGroup);
            
            if(baseContents == null || baseContents.isEmpty())
            {
                printError("Overrides group not found: %s".formatted(overrides), element);
                return;
            }
            
            finalContents.putAll(baseContents);
            
            currentDefinedContents.forEach(
                (lang, content) ->
                {
                    if(content.contains(SUPER))
                    {
                        final var baseText = baseContents.getOrDefault(lang, "");
                        finalContents.put(lang, content.replace(SUPER, baseText));
                    }
                    else
                        finalContents.put(lang, content);
                }
            );
        }
        else
            finalContents.putAll(currentDefinedContents);
        
        if(group != null)
        {
            final var fullGroup = "%s:%s".formatted(namespace, group);
            if(groups.containsKey(fullGroup))
                printError("Group %s redefined!".formatted(fullGroup), element);
            groups.put(fullGroup, new HashMap<>(finalContents));
        }
        
        if(translationLookup.containsKey(key))
            printError("Key %s duplicated!".formatted(key), element);
        
        translationLookup.put(key, finalContents);
    }
    
    private @NotNull HashMap<Lang, String> parseTranslationContents(@NotNull Element element, @Nullable String @Nullable [] translations, @Nullable String overrides)
    {
        if(translations == null || translations.length == 0)
            return new HashMap<>();
        
        final var translationContents = new HashMap<Lang, String>();
        
        for(int index = 0; index < translations.length; index++)
        {
            final String entry = translations[index];
            
            if(entry == null || entry.isEmpty())
                return new HashMap<>();
            
            final Matcher matcher = TRANSLATION_PATTERN.matcher(entry);
            
            if(!matcher.matches())
                printError(
                    "Mismatched translation grammar: %s -> at %s, index %d".formatted(entry, element.getSimpleName().toString(), index),
                    element
                );
            
            final String lang = matcher.group(1);
            final String content = matcher.group(2).replace(WHITESPACE, " ");
            
            if(!hasContent(lang))
                printError(
                    "Language is empty -> at %s, index %d".formatted(element.getSimpleName().toString(), index),
                    element
                );
            
            if(!hasContent(content))
                printError(
                    "Content is empty -> at %s, index %d".formatted(element.getSimpleName().toString(), index),
                    element
                );
            
            if(overrides == null && content.contains(SUPER))
                printError(
                    "Content has specified `~@^` to use super's content text, but it doesn't have a group to override!",
                    element
                );
            
            final Lang language = Lang.parse(lang);
            
            if(language != null)
                translationContents.put(language, content);
            else
                printError("Language %s doesn't exist!".formatted(lang), element);
        }
        
        return translationContents;
    }
    
    private @NotNull HashMap<Lang, HashMap<String, String>> composeTranslationTable()
    {
        final HashMap<Lang, HashMap<String, String>> translationTable = new HashMap<>();
        for(final var set: translationLookup.entrySet())
        {
            final var key = set.getKey();
            final var contents = set.getValue();
            
            for(final var contentEntry: contents.entrySet())
            {
                final var lang = contentEntry.getKey();
                final var content = contentEntry.getValue();
                
                final var map = translationTable.computeIfAbsent(lang, $ -> new HashMap<>());
                
                if(map.containsKey(key))
                    printError("Duplicated translation key -> key: %s".formatted(key));
                
                map.put(key, content);
            }
        }
        return translationTable;
    }
    
    private void generateJSON(@NotNull HashMap<Lang, HashMap<String, String>> translationTable)
    {
        translationTable.forEach(
            (lang, translationMap) ->
            {
                try(final var writer = getWriter(lang))
                {
                    final String generatedHeader = lang.equals(Lang.LOL_US) ? UWU_HADR : STANDARD_GENERATE_HEADER;
                    
                    writer.write(generatedHeader);
                    final List<String> keys = new ArrayList<>(translationMap.keySet());
                    keys.sort(String::compareTo);
                    
                    for(int index = 0; index < keys.size(); index++)
                    {
                        final String key = keys.get(index);
                        final String content = translationMap.get(key);
                        final String entry = ENTRY_TEMPLATE.apply(key, content);
                        writer.write(entry);
                        
                        if(index < keys.size() - 1)
                            writer.write(",");
                        writer.write("\n");
                    }
                    
                    writer.write("}");
                    messager.get().printMessage(
                        Diagnostic.Kind.NOTE,
                        "Generated %s.json.".
                            formatted(lang.getCode())
                    );
                }
                catch(IOException e) { printError("Can't create JSON file. Details: %s".formatted(e.getMessage())); }
            }
        );
    }
    //endregion
    
    //region Private Utils
    private void printError(@NotNull String message) { this.printError(message, null); }
    
    private void printError(@NotNull String message, @Nullable Element element)
    {
        if(element == null)
            this.messager.get().printMessage(Diagnostic.Kind.ERROR, message);
        else
            this.messager.get().printMessage(Diagnostic.Kind.ERROR, message, element);
    }
    
    private @NotNull Writer getWriter(@NotNull Lang lang) throws IOException
    {
        if(this.outputPath == null)
        {
            return filer.get().createResource(
                StandardLocation.SOURCE_OUTPUT,
                "",
                "assets/%s/lang/%s.json".formatted(this.namespace, lang.getCode())
            ).openWriter();
        }
        
        final File dir = new File(this.outputPath, "assets/%s/lang/".formatted(this.namespace));
        
        if(!dir.exists() && !dir.mkdirs())
            printError("Can't create directory: %s".formatted(this.outputPath));
        
        final File file = new File(dir, "%s.json".formatted(lang.getCode()));
        
        return new BufferedWriter(new OutputStreamWriter(Files.newOutputStream(file.toPath()), StandardCharsets.UTF_8));
    }
    
    private static @NotNull String escape(@NotNull String text)
    {
        return text.replace("\\", "\\\\").
            replace("\"", "\\\"").
            replace("\n", "\\n").
            replace("\r", "\\r").
            replace("\t", "\\t");
    }
    
    @Contract(value = "null -> false", pure = true)
    @SuppressWarnings("BooleanMethodIsAlwaysInverted")//! Inverting name will make meaning of this method confusing.
    private static boolean hasContent(@Nullable String string) { return string != null && !string.isBlank(); }
    
    @Contract(value = "null -> false", pure = true)
    private static boolean hasContent(@Nullable String @Nullable [] strings)
    {
        if(strings == null)
            return false;
        
        for(final @Nullable String string: strings)
            if(!hasContent(string))
                return false;
        
        return true;
    }
    
    private static @Nullable String getOrNull(String string)
    {
        if(hasContent(string))
            return string;
        return null;
    }
    
    private static @Nullable String @Nullable [] getOrNull(String[] strings)
    {
        if(hasContent(strings))
            return strings;
        return null;
    }
    
    private int inTypes(@NotNull TypeMirror mirror)
    {
        final var typeUtil = this.typeUtil.get();
        
        for(int index = 0; index < types.size(); index++)
        {
            final @Nullable TypeMirror typeMirror = typeUtil.erasure(types.get(index));
            
            if(typeUtil.isSameType(typeMirror, object.get()))
            {
                printError("The type at index %d seems to be null. Stopping procession.".formatted(index));
                return UNSUPPORTED_INDEX;
            }
            
            if(typeUtil.isAssignable(mirror, typeMirror))
                return index;
        }
        
        return UNSUPPORTED_INDEX;
    }
    //endregion
}
