//==============================================================================
// Copyright (C) 2026 Kurv Cygnus                                              =
// This file is part of Crisp Sweetberry.                                      =
// Crisp Sweetberry is free software: you can redistribute it and/or modify    =
// it under the terms of the GNU Lesser General Public License as published by =
// the Free Software Foundation, either version 3 of the License.              =
//==============================================================================

//? This is the build script of I18n API's generator.

//? Main Build Script: [[../build.gradle]]
//? API Build Script: [[../i18n-api/build.gradle]]

//? Necessary SPI Declarations:
//* Javax: [[./src/main/resources/META-INF/services/javax.annotation.processing.Processor]]
//* Gradle: [[./src/main/resources/META-INF/gradle/incremental.annotation.processors]]

//* Processor Core: [[I18nProcessor]]

plugins {
    id 'java-library'
}

group = mod_group_id
version = mod_version

repositories {
    mavenCentral()
}

dependencies {
    version = project.neo_version
    implementation(project(':i18n-api'))
    compileOnly "org.jetbrains:annotations:24.1.0"
}

test {
    useJUnitPlatform()
}