name: Build Validation

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # Elephant 🐘
          cache: 'gradle'

      - name: Make Gradle executable
        #! This is a classic issue. See https://stackoverflow.com/questions/17663363/permission-denied-for-gradlew.
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -PgithubCI